# Need to sync this to the frontend.
frontend:
  endpoint: 'http://127.0.0.1:10000'

backend:
  ip: '0.0.0.0'
  port: 10000
  db: "mongodb://127.0.0.1:32769/?directConnection=true"

files:
  champ_alias: 'config/champ_aliases.csv'
  item_alias: 'config/item_aliases.csv'
  trait_alias: 'config/trait_aliases.csv'

tft:
  set: 'TFTSet16'
  cluster_id: 386
  days: 1
  patch: 'current'
  # Supported ranks: BRONZE,CHALLENGER,DIAMOND,EMERALD,GOLD,GRANDMASTER,IRON,MASTER,PLATINUM,RANKUNKNOWN,SILVER
  ranks:
    - 'CHALLENGER'
    - 'DIAMOND'
    - 'EMERALD'
    - 'MASTER'
    - 'PLATINUM'